version: '3.7'

services:
  auditor:
    container_name: auditor
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /github/workspace
    volumes:
      - ./examples/example-1:/github/workspace
